server:
  port: 8180
#注册中心
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.1.108:7001/eureka/
  instance:
    instance-id: msm8180
    prefer-ip-address: true #访问路径可以显示ip地址

feign:
  hystrix:
    enabled: true
#设置feign客户端超时时间（OpenFeign默认支持ribbon）
ribbon:
  #指的是建立连接所用的时间，适用于网络状态正常的情况下，两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000
spring:
  application:
    name: service-sms
  zipkin:
    base-url: http://192.168.1.108:9411
  sleuth:
    sampler:
      probability: 1
  redis:
    host: 110.42.224.240
    port: 6379
    database: 0
    password: 1410357039 #默认为空
    timeout: 3000ms #最大等待时间，超时则抛出异常，否则请求一直等待
    lettuce:
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 8     #最大空闲连接，默认8
        min-idle: 0     #最小空闲连接，默认0

#腾讯云短信
tencent:
  sms:
    secretId: AKIDYAi8RcfZL0XxKahqsoeNOJWccUErNpCR
    secretKey: CHF5nMn6HQVVOK8qVyEF2bv0pQnulNks
    #短信应用 ID
    appid: 1400592492
    #短信签名内容
    sign: Jzj的Java学习之路
    #短信模板ID
    templateID: 1188682

